version: '3'

services:
    php:
        build: .
        image: php
        container_name: php
        restart: always
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html
        network_mode: host
